

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS base
WORKDIR /app

WORKDIR /src
COPY BoaSaude.sln ./
COPY Domain/*.csproj ./Domain/
COPY Application/*.csproj ./Application/
COPY Infrastructure/*.csproj ./Infrastructure/
COPY API/*.csproj ./API/

RUN dotnet restore
COPY . .

WORKDIR /src/Domain
RUN dotnet build -c Release -o /app

WORKDIR /src/Application
RUN dotnet build -c Release -o /app

WORKDIR /src/Infrastructure
RUN dotnet build -c Release -o /app

WORKDIR /src/API
RUN dotnet build -c Release -o /app

RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 
WORKDIR /app
COPY --from=base /app .
ENTRYPOINT ["dotnet","API.dll"]